version: '2.3'

services:
  gpd:
    image: "nvidia_gpd:latest"
    container_name: "gpd"
    command: "bash"
    init: true
    ports:
      - 8000:8000
      - 8888:8888
    stdin_open: true
    tty: true
    network_mode: "host"
    security_opt:
      - apparmor:unconfined

devenv:
  version: '1.0'
  rl:
    user: "r1-user"
    project_dir: "$HOME/elena_ws/heap"
    resources:
      directories:
        - "$HOME/.dockerdot/atom:$HOME/.atom"
        - "$HOME/.dockerdot/config/atom:$HOME/.config/Atom"
        - "$HOME/.dockerdot/ccache:$HOME/.ccache"
        - "$HOME/.dockerdot/gitkraken:$HOME/.gitkraken"
        - "$HOME/.dockerdot/config/qtcreator:$HOME/.config/QtProject"
        - "$HOME/.dockerdot/PyCharmCE2019.3/:$HOME/.PyCharmCE2019.3"
        - "$HOME/.dockerdot/cache:$HOME/.cache"
      files:
        - "$HOME/.dockerdot/bash_history:$HOME/.bash_history"
    gpu: "nvidia"
    x11: "xauth"
    gdb: true
    git:
      username: "Elena Rampone"
      email: "elena.rampone@iit.it"
